spring:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_5_DEVINT?useSSL=false&allowPublicKeyRetrieval=true
    username: CSCI5308_5_DEVINT_USER
    password: ahthi6ohHe

    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: DalhousingEase
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format:_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB